config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get '/users/sign_out' => 'devise/sessions#destroy'

  get 'my_products', to: 'products#my_products'

  get '/bookings/:id/accept', to: 'bookings#accept', as: 'accept_booking'
  get '/bookings/:id/reject', to: 'bookings#reject', as: 'reject_booking'

  resources :products do
    resources :bookings, only: %i[new create]

    collection do
      get :search
    end

    member do
      get :reviews
    end

    resources :bookings, only: %i[new index create]
  end

  resources :bookings, except: %i[new index create] do
    resources :reviews, only: %i[new create]
  end

  resources :reviews, except: %i[new create]

  get '/bookings', to: 'bookings#index'

  get '/error', to: 'errors#not_found'

  get "*path", to: redirect("/error")
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :product
  belongs_to :user

  has_one :review, dependent: :destroy

  validates :total_price, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_user
  before_action :set_booking, only: %i[show edit update destroy]
  before_action :set_product, only: %i[new create]

  def accept
    @booking = Booking.find(params[:id])
    authorize @booking, :accept?
    @booking.update(status: "accepted")
    if @booking.product.update(status: true)
    redirect_to my_products_path, notice: "Réservation acceptée"
    else
      render :new
    end
  end

  def reject
    @booking = Booking.find(params[:id])
    authorize @booking, :reject?
    @booking.update(status: "rejected")
    @booking.product.update(status: false)
    redirect_to my_products_path, notice: "Réservation refusée"
  end

  def index
    @bookings = Booking.all
   # @bookings = policy_scope(Booking)
    # @my_bookings = policy_scope(Booking)
    @my_bookings = Booking.where(user_id: current_user.id)
    @my_products_booked = current_user.products.map(&:bookings).flatten
    #@bookings = current_user.products.map(&:bookings).flatten.select { |b| b.status == "pending" }
  end

  def new
    @booking = Booking.new
    authorize @booking
  end

  def show
    # authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user_id = @user.id
    @booking.product_id = @product.id
    @booking.total_price = total_price(@booking, @product)
  # @booking.total_price = ((@booking.end_date - @booking.start_date).to_i) * @product.price
    # authorize @booking
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def edit
    # authorize @booking
  end

  def update
    new_id = @booking.product_id
    @product = Product.find(new_id)
    @booking.update(booking_params)
    @booking.total_price = total_price(@booking, @product)

   # @booking.total_price = ((@booking.end_date - @booking.start_date).to_i) * @product.price
    # authorize @booking
    if @booking.save
      redirect_to booking_path(@product, @booking)
    else
      render :edit
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    # authorize @booking
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def total_price (booking, product)
    (((@booking.end_date - @booking.start_date).to_i) * @product.price)/7
  end

  def set_product
    @product = Product.find(params[:product_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_user
    @user = current_user
  end


  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :status, :total_price)
  end

  def skip_pundit?
    true
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
  <%= simple_form_for [@product, @booking] do |f| %>
      <div class="d-flex justify-content-between">
        <%= f.input :start_date, html5: true %>
        <%= f.input :end_date, html5: true %>
      </div>
      <%= f.submit "Submit", {class: "btn btn-primary w-100 mb-2"} %>
  <% end %>

app/views/bookings/edit.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
   <h2 class="display-1 pt-5">Modifier votre reservation</h2>
  </div>
</div>

<div class="container">
  <%= simple_form_for [ @booking ] do |f| %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.input :status %>
  <%= f.submit "Mettre à jour", class: "btn btn-outline-primary" %>
<% end %>
</div>

app/views/bookings/index.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
   <h2 class="display-1 pt-5">Vos reservation</h2>
  </div>
</div>

<div class="py-5">
  <div class="container">
    <div class="row hidden-md-up">
      <% @bookings.each do |booking| %>
        <% product = Product.find(booking.product_id) %>
        <div class="col-md-4">
          <div class="card mb-2">
            <div class="card-block p-3">
              <% if product.photo.key.present? %>
                <%= cl_image_tag booking.product.photo.key, crop: :fill, class:"product_pic card-img-top" %>
              <% else %>
                <%= image_tag("unknown.jpg", class:"product_pic card-img-top") %>
              <% end %>
              <p class="card-title">Ville: <%= product.city %></p>
              <p class="card-subtitle text-muted"><span class="font-weight-bold">Prix ​​total:</span> <%= booking.total_price %> Euros</p>
              <small class="card-text p-y-1"><span class="font-weight-bold">Description:</span> <%= product.description %> people</small><br>
              <%= link_to 'Vérifiez-le!', booking_path(booking), class: "btn btn-outline-primary" %> <br>

                <%= link_to 'Éditer', edit_booking_path(booking), class: "btn btn-outline-primary" %>

                <%= button_to 'Supprimer', @booking, method: :delete, data: {confirm: "Etes vous sur ?"}, class: "btn btn-outline-primary" %>

            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="row">
      <div class="container">

          <%= link_to "Retour à tous les produits !", products_path, class:"btn btn-outline-primary" %>

        <%= link_to 'Tous vos avis', reviews_path, class: "btn btn-outline-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
   <h2 class="display-1 pt-5">Mes demandes</h2>
  </div>
</div>

<div class="container ">
  <div class="card justify-content-center">
  <h1>Ma demande de réservation pour <%= @product.title %></h1>
  <p>Produit : <%= @product.title %></p>
  <p>Description : <%= @product.description %>
    <div class="card-body w-80 pt-4">
      <%= simple_form_for [@product, @booking] do |f| %>
      <div class="col-4">
        <%= f.input :start_date, label: 'Date de début souhaitée', as: :date, html5: true, order: [:day, :month, :year]  %>
      </div>
      <div class="col-4">
        <%= f.input :end_date, label: 'Date de fin souhaitée', as: :date, html5: true, order: [:day, :month, :year] %>
      </div>
      <div class="col-4">
        <%= f.submit "Faire une demande", class: "btn btn-success" %>

      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
   <h2 class="display-1 pt-5">Votre reservation</h2>
  </div>
</div>

<% product = Product.find(@booking.product_id) %>
<div class="container">
  <div class="row d-flex align-items-center">
    <div class="col-8">
      <h3>Votre reservation a <%= product.city %> </h3>
    </div>
  </div>
  <div class="row booking_container">
    <div class="col-6">
      <% if product.photo.key.present? %>
        <%= cl_image_tag product.photo.key, crop: :fill, class:"product_pic booking_product_pic" %>
      <% else %>
        <%= image_tag("unknown.jpg", class:"product_pic booking_product_pic") %>
      <% end %>
    </div>
    <div class="info show_booking col-4">
      <p style="font-size: 16px;"><span class="font-weight-bold">À partir de: </span><%= @booking.start_date.strftime("%e-%m-%Y")  %></p>
      <p style="font-size: 16px;"><span class="font-weight-bold">jusqu'a: </span><%= @booking.end_date.strftime("%e-%m-%Y")  %></p>
      <p style="font-size: 16px;"><span class="font-weight-bold">Title: </span><%= product.title  %></p>
      <p style="font-size: 16px;"><span class="font-weight-bold">Addresse: </span><%= product.address  %></p>
      <p style="font-size: 16px;"><span class="font-weight-bold">Description: </span><%= product.description  %></p>
      <p style="font-size: 16px;"><span class="font-weight-bold">Nombre de piéces: </span><%= product.stock  %></p>
      <p style="font-size: 16px;"><span class="font-weight-bold">Ville: </span><%= product.city  %></p>
      <p style="font-size: 16px;"><span class="font-weight-bold">Total Price: </span><%= @booking.total_price  %> € </p>
    </div>
    <div class="col-4 d-flex justify-content-start">

    </div>
  </div>
  <div class="booking-options">
    <%= link_to "Supprimer cette réservation", booking_path(@booking), method: :delete, data: { confirm: "Êtes-vous sûr?" }, class: "btn btn-primary mx-2" %>

      <%= link_to 'Modifier cette réservation', edit_booking_path(@booking), class: "btn btn-primary mx-2" %>

      <%= link_to 'Retour à vos réservations', bookings_path, class: "btn btn-primary mx-2" %>

  </div>
</div>