config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get '/users/sign_out' => 'devise/sessions#destroy'

  get 'my_products', to: 'products#my_products'

  get '/bookings/:id/accept', to: 'bookings#accept', as: 'accept_booking'
  get '/bookings/:id/reject', to: 'bookings#reject', as: 'reject_booking'

  resources :products do
    resources :bookings, only: %i[new create]

    collection do
      get :search
    end

    member do
      get :reviews
    end

    resources :bookings, only: %i[new index create]
  end

  resources :bookings, except: %i[new index create] do
    resources :reviews, only: %i[new create]
  end

  resources :reviews, except: %i[new create]

  get '/bookings', to: 'bookings#index'

  get '/error', to: 'errors#not_found'

  get "*path", to: redirect("/error")
end

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon p-2">
  <%= link_to root_path do %>
    <%= image_tag 'logo2.png' %>
  <% end %>
    <%= form_with url: products_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control rounded-pill col-6 me-3",
        placeholder: "Trouver une sculpture"
      %>
      <%= submit_tag "Search", class: "btn btn-outline-primary rounded-pill col-4" %>
    <% end %>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= image_tag "sign_in.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <span class="nav-link">Profil - <%= current_user.email %></span>
              <%= link_to "Mes produits", my_products_path, class: "dropdown-item" %>
              <%= link_to "Ajouter un produit", new_product_path, class: "dropdown-item" %>
              <%= link_to "Mes réservations", bookings_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Connexion", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
    </ul>
  </div>
</div>