config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get '/users/sign_out' => 'devise/sessions#destroy'

  get 'my_products', to: 'products#my_products'

  get '/bookings/:id/accept', to: 'bookings#accept', as: 'accept_booking'
  get '/bookings/:id/reject', to: 'bookings#reject', as: 'reject_booking'

  resources :products do
    resources :bookings, only: %i[new create]

    collection do
      get :search
    end

    member do
      get :reviews
    end

    resources :bookings, only: %i[new index create]
  end

  resources :bookings, except: %i[new index create] do
    resources :reviews, only: %i[new create]
  end

  resources :reviews, except: %i[new create]

  get '/bookings', to: 'bookings#index'

  get '/error', to: 'errors#not_found'

  get "*path", to: redirect("/error")
end

app/models/product.rb
class Product < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  belongs_to :user

  has_many :bookings, dependent: :destroy

  has_one_attached :photo
  has_many :reviews, through: :bookings

  validates :title, presence: true, uniqueness: true
  validates :description, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :price, presence: true
  validates :status, presence: true
  validates :stock, presence: true

  def status?
    status
  end

  include PgSearch::Model
  pg_search_scope :search_by_city_address,
    against: [ :city, :address ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  def average_rating
    if self.bookings.empty?
      return {
        average: 0,
        num: 0
      }
    else
      ratings = []
      number = 0
      self.bookings.each do |booking|
        if booking.review
          number += 1
          ratings << booking.review.rating
        else
          next
        end
      end
      if ratings.empty?
        return {
          average: 0,
          num: 0
        }
      else
        return {
          average: ((ratings.sum) / ratings.count),
          num: number
        }
      end
    end
  end

  def reviews
    reviews = []
    unless self.bookings.empty?
      self.bookings.each do |booking|
        reviews << booking.review if booking.review
      end
    end
    return reviews
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  before_action :set_user, :database_search
  before_action :set_product, only: %i[show edit update destroy reviews]

  def index
    @products = Product.all
    #@products = policy_scope(Product)
    @markers = @products.geocoded.map do |product|
      {
        lng: product.longitude,
        lat: product.latitude,
        info_window_html: render_to_string(partial: "info_window", locals: {product: product}),
        marker_html: render_to_string(partial: "marker", locals: {product: product})
      }
    end
  end

  def new
    @product = Product.new
    # authorize @product
  end

  def create
    @product = Product.new(product_params)
    @product.user_id = @user.id
    @product = current_user.products.build(product_params)
    # authorize @product
    if @product.save
     flash[:notice] = "Product successfully listed for sale!"
     redirect_to @product
    else
     flash[:alert] = "Failed to list product for sale. Please try again."
     render :new
    end
  end

  def show
    @product = Product.find(params[:id])
    @booking = Booking.new
    @bookings = @product.bookings.where(status: "pending")
  end

  def edit
    Product.find(params[:id])
    # authorize @product
  end

  def update
    @product.update(product_params)
    @booking = @product.bookings.find(params[:booking_id])
    if params[:status] == false
      @booking.update(status: "accepted")
      flash[:notice] = "Booking request accepted!"
    elsif params[:status] == false
      @booking.update(status: "rejected")
      flash[:notice] = "Booking request rejected!"
    else
      flash[:alert] = "Invalid status. Please try again."
    end
    redirect_to @product
  end

  def destroy
  #  authorize @products
    @product.destroy
    redirect_to my_products_url, notice: "Restaurant was successfully destroyed."
  end

  def my_products
    @products = current_user.products
    @bookings = @products.map {|p| p.bookings}.flatten
    # authorize @products
  end

  def search
    if params[:query].present?
      @products = Product.search_by_city_address(params[:query])
    else
      @products = Product.all
    end
    @count = @products.count
    @query = params[:query]

    @markers = @products.geocoded.map do |product|
      {
        lat: product.latitude,
        lng: product.longitude,
        info_window: render_to_string(partial: "info_window", locals: { product: product }),
        marker_html: render_to_string(partial: "marker", locals: {product: product})
      }
    end
    authorize @products
    authorize @markers
  end

  def reviews
    unless @product.reviews.empty?
      @reviews = @product.reviews
    end
  end

  def status
    @products = Product.where(status: params[:status])
  end

  def my_bookings
    @bookings = Booking.where(user: current_user)
  end

  def my_bookings_as_owner
    @bookings = Booking.where(product: current_user.products)
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :address, :city, :photo, :capacity, :price, :latitude, :longitude, :start_date, :end_date, :status)
  end

  def set_product
    if Product.find_by(id: params[:id]).nil?
      redirect_to error_path
    else
      @product = Product.find(params[:id])
      # authorize @product
    end
  end

  def set_user
    @user = current_user
  end

  def database_search
    @markers = Product.all
  end

  def skip_pundit?
    true
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
   <h2 class="display-1 pt-5">Modifier produits</h2>
  </div>
</div>

<div class="container">
  <div class="rental_form">
    <%= simple_form_for [ @product ] do |f| %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :address %>
      <%= f.input :city %>
      <%= f.input :price %>
      <%= f.input :stock %>
      <%= f.input :status, label: 'Would you like to make this property immediately available?' %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Modifier produits", class: "btn btn-outline-success" %>
    <% end %>
  </div>
</div>

app/views/products/_info_window.html.erb
<%= link_to product do %>
    <% if product.photo.key.nil? %>
    <%= image_tag "no-image.png", class:"img-fluid width: 100% height: auto" %>
  <% else %>
    <%= cl_image_tag product.photo.key, crop: :fill, class:"img-fluid width: 100% height: auto" %>
  <% end %>

  <div class="map-card">
    <p><span class="font-weight-bold" style="font: size 15px;"><i class="fa fa-location-arrow"></i></span>  <%= product.address %> <strong></strong></p>
    <p><span class="font-weight-bold" style="font-size:15px;"><i class="fa fa-user"></i></span>  <%= product.title %> </p>
    <p>€/semaine <span class="font-weight-bold" style="font-size:30px; text-align:right; font-family:"><%= product.price %></span></p>
  </div>
<% end %>

app/views/products/_marker.html.erb
<%= image_tag "sign_in.png", height: 50, width: 50, alt: "logo" %>

app/views/products/_product.html.erb
<div class="container margin-top-negative">
  <div class="card">
    <div id="<%= dom_id product %>">
     <% if @product.photo.attached? %>
      <%= cl_image_tag @product.photo.key, class: 'show-image' %>
      <% else %>
      <%= image_tag("unknown.jpg", class:"show-image") %>
     <% end %>
    </div>

    <div class="col-8">
      <div class="product-show-card">
        <h1><%= @product.title %></h1>
        <p class="product-show-address"><%= @product.address %></p>
      </div>
      <div class="product-show-card">
        <p><strong>Description: </strong><%= @product.description %></p>
        <p><strong>Prix ​​par jour: </strong><%= @product.price %> €</p>
        <p><strong>Stock: </strong><%= @product.stock %> piéces</p>

        <% if @product.status? %>
          <p class="card-text text-success"><strong>Disponible</strong></p><br>
        <% else %>
          <p class="card-text"><strong>Indisponible</strong></p><br>
        <% end %>
        <%= link_to "Louer", "/products/#{params[:id]}/bookings/new", class: "btn btn-info" %>

      </div>
      <div class="col-8">
        <div class="product-show-card">
          <h5>Louer cette belle pieces!</h5>

          <div class="container property-booking-tool">
            <div class="booking-tool-header">

              <h2 class="p-0 my-3">Make a booking:</h2>
              <div class="price-header">
                 <p class="text-success"> <%= number_to_currency(@product.price, unit: "£", precision: 0) %> / night </p>
              </div>
            </div>
            <div class="dates w-100 pb-2">
              <%= render 'bookings/form', booking: Booking.new, property: @property %>
            </div>
          </div>
        </div>
        </div>

        <div class="product-show-card">
          <div class="flex-align">
           <hr>
           <div>
            <%= link_to "Edit this product", edit_product_path(@product) %> |
            <%= link_to "Back to products", products_path %>
            <%= button_to "Destroy this product", @product, method: :delete, class: "btn btn-danger" %>
           </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <hr>
  <h6 class="no-mb">Share</h6>
  <div class="flex">
    <i class="fa-brands fa-facebook-square me-2"></i>
    <i class="fa-brands fa-twitter-square me-2"></i>
    <i class="fa-brands fa-pinterest-square me-2"></i>
  </div>
</div>

app/views/products/edit.html.erb
<%= render 'form' %>

app/views/products/index.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
   <h2 class="display-1 pt-5">Ensembles À Louer</h2>
  </div>
</div>

<div class="px-5 products-map-grid">
  <div id='map' style='width: 100%;'
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

  <div class="product-cards">
    <% @products.each do |product| %>
      <div class="card mb-2">
        <div class="card-block p-3">
          <div class="products-photo">
            <% if product.photo.attached? %>
              <%= cl_image_tag product.photo.key, class: 'card-img-top index-image' %>
            <% else %>
            <%= image_tag("unknown.jpg", class:"card-img-top my_product_image index-image") %>
            <% end %>
            <h5 class="card-title text-center"><%= link_to product.title, product_path(product) %></h5>
            <p class="card-text"><%= product.description %></p>
            <p class="card-text"><%= product.price %> €/ jours</p>
            <%= link_to "Voir le produit", product, class: "rounded-pill btn btn-outline-warning" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/my_products.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
   <h2 class="display-1 pt-5">Mes produits !!</h2>
  </div>
</div>

<div class="my_products_page">
  <div class="my_products_container">

    <% unless current_user.products.nil? %>
      <% @products.each do |product| %>
        <div class="product_row">
          <div class="photo">
            <% if product.photo.key.present? %>
              <%= cl_image_tag(product.photo.key, class:"my-product-image") %>
            <% else %>
              <%= image_tag("unknown.jpg", class:"my-product-image") %>
            <% end %>
            <p><%= product.address %></p>
          </div>

          <div class="d-flex align-items-center">
            <%= link_to 'Edit', edit_product_path(product), class:"btn btn-primary" %>
            <% unless product.bookings.any? %>
              <div class="remove_product_button">
                <%= link_to product_path(product), method:"delete", data: { confirm: "Are you sure?" }, class:"bin" do %>
                <i class="fa fa-trash" aria-hidden="true"></i>
              </div>
            <% end %>
          </div>
          <% else %>
          <div class="remove_product_button_disabled">
            <i class="fa fa-trash" aria-hidden="true" title="This product has ongoing booking"></i>
          </div>
          <% end %>

        </div>
        <hr>
      <% end %>
    <% end %>
    <div class="d-flex align-items-center">
    <%= link_to "Add a new product", new_product_path(@product), class:"btn btn-primary add_new_product" %>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
   <h2 class="display-1 pt-5">Ajouter un produits</h2>
  </div>
</div>

<div class="container">
  <div class="rental_form">
    <%= simple_form_for [ @product ] do |f| %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :price %>
      <%= f.input :city %>
      <%= f.input :address %>
      <%= f.input :stock %>
      <%= f.input :status %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Ajouter produits", class: "btn btn-outline-primary" %>
    <% end %>
  </div>
</div>

app/views/products/reviews.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
   <h1 class="display-1 pt-5">Mes avis</h1>
  </div>
</div>

<h1><span class="text-muted"><%= @product.address %></span> Reviews (<%= @product.reviews.count %> opinions)</h1>
<div class="container">
  <div class="row d-flex justify-content-center">
   
  </div>
  <%= link_to 'Back to product', product_path(@product), class: "btn btn-primary" %>
</div>

app/views/products/search.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
   <h2 class="display-1 pt-5">Produits disponibles</h2>
  </div>
</div>

<% @search_colon = @query.present? ? ":" : ""  %>
<% @search_text =  @count > 1 || @count == 0 ? "stays" : "stay" %>
<h1 class="text-center">Tous les produits disponibles</h1>
<h3 class="text-center"><%= @query.capitalize %> <%= @search_colon %> <%= @count %> <%=@search_text %> found </h3>
<div class="px-5 products-map-grid">
    <div id='map' style='width: 100%;'
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  <div class="product-cards">
    <% @products.each do |product| %>
    <div>
      <div class="card mb-2">
        <div class="card-block p-3">
          <div class="products-photo">
            <% if product.photo.key.present? %>
              <%= cl_image_tag product.photo.key, class:"card-img-top search-image " %>
            <% else %>
            <%= image_tag("unknown.jpg", class:"card-img-top search-image") %>
            <% end %>
          </div>
          <strong><p class="card-title"><%= product.address %></p></strong>
          <p class="card-subtitle text-muted"><span class="font-weight-bold">Price:</span> <%= product.price %> Euros</p>
          <small class="card-text p-y-1"><span class="font-weight-bold">Capacity:</span> <%= product.capacity %> people</small><br>
          <%= link_to 'Check it out!', product, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>
<h1><%= link_to "Retournez à la page d'accueil", root_path, class: "btn btn-primary" %></h1>

app/views/products/show.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-white">
   <h2 class="display-1 pt-5">Ensembles À Louer</h2>
  </div>
</div>

<p style="color: green"><%= notice %></p>

<%= render @product %>